---
- name: Remove Existing Files in Folder
  file:
    path: /usr/share/nginx/html/
    state: absent
    
- name: Deploy the Application
  git: 
    repo: 'https://github.com/samfil-technohub/samfil-technohub-landingpage-app.git'
    dest: /usr/share/nginx/html
  changed_when: true
  notify:
    - Reload Daemon