---
- name: Create Application Directory
  file: 
    path: "/var/www/html"
    state: directory
    owner: root
    group: www-data

- name: Make the /var/www/html Empty
  file:
    path: /var/www/html/
    state: absent
    
- name: Deploy the Application
  git: 
    repo: 'https://github.com/knoxknot/landingpage.git'
    dest: /var/www/html
  changed_when: true